excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - clientAppUITests
  
disabled_rules: # rule identifiers to exclude from running

line_length:
  - 160 # warning

identifier_name:
  severity: warning # explicitly